# Generated by Django 4.2.19 on 2025-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=255)),
                ('concours_souhaite', models.CharField(choices=[('TWIN', 'Technologie du Web et Image Numerique'), ('Srit', 'Sytemes et Reseaux Informatiques et Telecom'), ('Mp2i', 'Classe préparatoire: Mathématiques Physique et Informatique')], max_length=4)),
                ('extrait_naissance', models.FileField(upload_to='documents/')),
                ('certificat_nationalite', models.FileField(upload_to='documents/')),
                ('lettre_motivation', models.FileField(upload_to='documents/')),
                ('diplome', models.FileField(upload_to='documents/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
